version: '3.8'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 znakapp.asgi:application
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: znakapp.settings
      PYTHONPATH: /app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
