# Generated by Django 4.2 on 2024-02-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.TextField()),
                ("amount", models.FloatField()),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
