# Generated by Django 4.2 on 2024-02-13 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0003_clearamount"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClearAmount",
            new_name="ClearCount",
        ),
    ]
