# Generated by Django 4.2 on 2024-02-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0004_rename_clearamount_clearcount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot_logined",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.TextField()),
                ("status", models.BooleanField()),
                ("nickname", models.TextField()),
            ],
        ),
    ]
