# Generated by Django 4.2 on 2024-02-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0005_bot_logined"),
    ]

    operations = [
        migrations.AddField(
            model_name="clearcount",
            name="bonus_count",
            field=models.IntegerField(default=0),
        ),
    ]
