# Generated by Django 4.2 on 2024-03-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0006_clearcount_bonus_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="advanced_price",
            new_name="advanced_price_eu",
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="beginner_price",
            new_name="advanced_price_tn",
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="beginner_access",
            new_name="beginer_access",
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="beginner_bonus",
            new_name="beginer_bonus",
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="expert_price",
            new_name="beginer_price_eu",
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="trial_price",
            new_name="beginer_price_tn",
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="beginner_quantity",
            new_name="beginer_quantity",
        ),
        migrations.AddField(
            model_name="cart",
            name="expert_price_eu",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="expert_price_tn",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="trial_price_eu",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="trial_price_tn",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
